name: Renovate config validator

on:
  pull_request:
    paths:
      - 'renovate.json'

jobs:
  lint-renovate-config:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
      - name: Use Node.js
        uses: actions/setup-node@949feb2413d6458794dcd2491c4babbbce0c15c1 # v7
        with:
          node-version: '24'
      - name: run renovate-config-validator
        run: |
          jq . renovate.json
          npx --yes --package renovate@latest -- renovate-config-validator --strict
